//
//  ErrorCode.h
//  DensoScannerSDK
//
//  Created by SP1 on 2018/08/29.
//  Copyright © 2018年 SP1. All rights reserved.
//

#import <Foundation/Foundation.h>

/**
 エラーコード
 
 - ERRORNO_COMMUNICATION_ERROR: スキャナとの通信エラー
 - ERRORNO_COMMUNICATION_TIMEOUT: スキャナからの応答タイムアウト
 - ERRORNO_SESSION_NOT_ESTABLISHED: セッション確立エラー
 - ERRORNO_HANDSHAKE_INVALID_FORMAT: ハンドシェイク不正フォーマット
 - ERRORNO_HANDSHAKE_NO_REQUIRED_ITEM: 未サポートスキャナ
 - ERRORNO_CLOSE_TIMEOUT: 停止タイムアウト
 - ERRORNO_TOO_MUCH_COMMAND_QUEUE: コマンドキューがあふれたとき
 - ERRORNO_INVALID_COMMAND: 無効オプション指定時
 - ERRORNO_INVALID_STATUS: 状態が不正なとき。claim 前に API を呼んだときや、 open していないのに close 呼び出しなど。
 - ERRORNO_INVALID_RESPONSE: 不正な応答がスキャナーからあったとき
 - ERRORNO_NOT_SUPPORT_COMMAND: スキャナが対応していないコマンド送信時
 - ERRORNO_ACCESS_OUT_OF_RANGE_MEMORY: メモリ範囲外へのアクセス
 - ERRORNO_SCANNER_ACCESS_LOCK_MEMORY: ロックメモリへのアクセス
 - ERRORNO_SCANNER_POWER_SHORTAGE_OF_WRITE_MEMORY: メモリライト電力不足
 - ERRORNO_SCANNER_WRITE_LOCK_KILL_TIMEOUT: 時間内に Write or Lock or Kill が完了しなかったとき
 - ERRORNO_SCANNER_WRITE_LOCK_KILL_UNKNOWN: Write or Lock or Kill エラー(理由不明)
 - ERRORNO_SCANNER_CHARGING: 充電中エラー(充電中はRFID読み取り不可)
 - ERRORNO_SCANNER_TRIGGER_MODE: トリガーモードエラー(未対応のトリガーモードで WRITE or LOCK or KILL 実行)
 - ERRORNO_INVAILD_OPERATION: 無効な操作をしたとき
 - ERRORNO_INVALID_MODEL: Firmwareファイルが当該スキャナの機種と一致しない
 - ERRORNO_INVALID_VERSION: ダウングレード時
 - ERRORNO_INVALID_FILE: Firmwareファイルが不正
 - ERRORNO_SCANNER_WRITE_FIRMWARE: Firmware書き込みエラー発生。SP1は自動的にPower offします。
 - ERRORNO_SCANNER_INCOMPLETE_UPGRADE: UPGRADE用通信エラーなどでUPGRADEが完了しない状態で終了したとき。SP1は自動的にPower offします。
 - ERRORNO_NULL_POINTER_EXCEPTION: Nullポインターにアクセスしたとき
 - ERRORNO_UNKNOWN: 原因不明です。
 - ERRORNO_NONE: エラー無し
 - ERRORNO_EXCUTE: ROMへの書き込み失敗
 */
typedef NS_ENUM(NSInteger, ErrorCode) {
    ERRORNO_COMMUNICATION_ERROR = 0x0001
    , ERRORNO_COMMUNICATION_TIMEOUT = 0x0002
    , ERRORNO_SESSION_NOT_ESTABLISHED = 0x0003
    , ERRORNO_HANDSHAKE_INVALID_FORMAT = 0x0004
    , ERRORNO_HANDSHAKE_NO_REQUIRED_ITEM = 0x0005
    , ERRORNO_CLOSE_TIMEOUT = 0x0006
    , ERRORNO_TOO_MUCH_COMMAND_QUEUE = 0x0007
    , ERRORNO_INVALID_COMMAND = 0x0008
    , ERRORNO_INVALID_STATUS = 0x0009
    , ERRORNO_INVALID_RESPONSE = 0x000A
    , ERRORNO_NOT_SUPPORT_COMMAND = 0x000B
    , ERRORNO_ACCESS_OUT_OF_RANGE_MEMORY = 0x000C
    , ERRORNO_SCANNER_ACCESS_LOCK_MEMORY = 0x000D
    , ERRORNO_SCANNER_POWER_SHORTAGE_OF_WRITE_MEMORY = 0x000E
    , ERRORNO_SCANNER_WRITE_LOCK_KILL_TIMEOUT = 0x000F
    , ERRORNO_SCANNER_WRITE_LOCK_KILL_UNKNOWN = 0x0010
    , ERRORNO_SCANNER_CHARGING = 0x0011
    , ERRORNO_SCANNER_TRIGGER_MODE = 0x0012
    , ERRORNO_INVAILD_OPERATION = 0x0013
    , ERRORNO_INVALID_MODEL = 0x0014
    , ERRORNO_INVALID_VERSION = 0x0015
    , ERRORNO_INVALID_FILE = 0x0016
    , ERRORNO_SCANNER_WRITE_FIRMWARE = 0x0017
    , ERRORNO_SCANNER_INCOMPLETE_UPGRADE = 0x0018
    , ERRORNO_NULL_POINTER_EXCEPTION = 0x0019
    , ERRORNO_UNKNOWN = 0xFFFF
    , ERRORNO_NONE = 0x0000
    , ERRORNO_EXCUTE =0x0020
    , ERRORNO_SCANNER_TEMP_ERROR =0x0021 // 温度エラー
    , ERRORNO_SCANNER_EPD_LOST =0x0301 // タグ消失
    , ERRORNO_SCANNER_EPD_CHARGE_TIMEOUT =0x0303 // タグ給電タイムアウト
    , ERRORNO_SCANNER_EPD_OPERATION_TIMEOUT =0x0304 // 書き込み処理タイムアウト
};
